 let phrases = [
            "I'm going to the bathroom to read. -Elvis Presley",
            "Goodbye, kid. Hurry back. -Humphrey Bogart",
            "I’m bored with it all. -Winston Churchill",
            "I have offended God and mankind because my work did not reach the quality it should have. -Leonardo da Vinci",
            "This dying is boring. -Richard Feynman",
            "My wallpaper and I are fighting a duel to the death. One or the other of us has to go. -Oscar Wilde",
            "I knew it, I knew it! Born in a goddamn hotel room and dying in a hotel room. -Eugene O’Neill",
            "I must go in; the fog is rising. -Emily Dickinson",
            "Here is the battle of day against night. I see black light.  -Victor Hugo",
            "Dammit, don’t you dare ask God to help me. -Joan Crawford",
            "Music has been my doorway of perception and the house that I live in. -David Bowie",
            "I can feel the daisies growing over me. -John Keats",
            "Last words are for fools who haven’t said enough! -Karl Marx",
            "I'm going away tonight. -James Brown",
            "Stand away, fellow, from my diagram! -Archimedes",
            "I want nothing but death. -Jane Austen",
            "Where is my clock? -Salvador Dalí",
            "One last drink, please. -Jack Daniel",
            "Oh, you young people act like old men. You are no fun. -Josephine Baker",
            "Shoot, coward, you are only going to kill a man. -Che Guevara",
            "Swing low, sweet chariot. -Harriet Tubman",
            "I feel great. -'Pistol' Pete Maravich",
            "A dying man can do nothing easy. -Benjamin Franklin",
            "Happy anniversary. I love you. -Vince Lombardi",
            "Tell Georgie I want to get in the movies one way or another. -Charles 'Lucky' Luciano",
            "God damn the whole friggin’ world and everyone in it but you, Carlotta. -W.C. Fields",
            "One never knows the ending. One has to die to know exactly what happens after death, although Catholics have their hopes. -Alfred Hitchcock",
            "This is no way to live! -Groucho Marx",
            "I want the world to be filled with white fluffy duckies. -Derek Jarman",
            "Goodnight, my kitten. -Ernest Hemingway",
            "Every damn fool thing you do in this life you pay for. -Edith Piaf",
            "Oh wow. Oh wow. Oh wow. -Steve Jobs",
            "Don't let it end like this. Tell them I said something. -Pancho Villa",
            "I finally get to see Marilyn. -Joe Dimaggio",
            "Lord help my poor soul. -Edgar Allan Poe",
            "You are wonderful. - Arthur Conan Doyle",
            "I understand the true principles of the government. I wish them carried out. I ask nothing more. -William Henry Harrison",
            "Perhaps it is best. -John Tyler",
            "I love you, Sarah. For all eternity, I love you. -James K. Polk",
            "I regret nothing, but I am sorry to leave my friends. -Zachary Taylor",
            "Oh, do not cry. Be good children and we shall meet in heaven. -Andrew Johnson",
            "I have tried so hard to do right. -Grover Cleveland",
            "I know I am going where Lucy is. -Rutherford B. Hayes",
            "I've been really sick lately, so I'm sorry that I haven't answered yours and Ernie's letters, but I think about you daily. -Moses Harry Horwitz",
            "That's what I anticipate death will be: a totally unconscious void in which you float through eternity with no particular consciousness about anything. -Rod Serling",
            "I’m going, but I’m going in the name of the Lord. -Bessie Smith",
            "What the devil do you mean to sing to me, priest? You are out of tune. -Jean-Philippe Rameau",
            "A certain butterfly is already on the wing. -Vladimir Nabokov",
            "You’re right. It’s time. I love you all. -Michael Landon"
        ];
        // both arrays are in sync, so the portrait corresponds to the same index of the phrase array
        let portraits = [
            'images/elvis-presley.jpg',
            'images/humphrey-bogart.jpg',
            'images/winston-churchill.jpg',
            'images/leonardo-da-vinci.jpg',
            'images/richard-feynman.jpg',
            'images/oscar-wilde.jpg',
            'images/eugene-o-neill.jpg',
            'images/emily-dickinson.jpg',
            'images/victor-hugo.jpg',
            'images/joan-crawford.jpg',
            'images/david-bowie.jpg',
            'images/john-keats.jpg',
            'images/karl-marx.jpg',
            'images/james-brown.jpg',
            'images/archimedes.jpg',
            'images/jane-austen.jpg',
            'images/salvador-dali.jpg',
            'images/jack-daniel.jpg',
            'images/josephine-baker.jpg',
            'images/che-guevara.jpg',
            'images/harriet-tubman.jpg',
            'images/pete-maravich.jpg',
            'images/benjamin-franklin.jpg',
            'images/vince-lombardi.jpg',
            'images/lucky-luciano.jpg',
            'images/wc-fields.jpg',
            'images/alfred-hitchcock.jpg',
            'images/groucho-marx.jpg',
            'images/derek-jarman.jpg',
            'images/ernest-hemingway.jpg',
            'images/edith-piaf.jpg',
            'images/steve-jobs.jpg',
            'images/pancho-villa.jpg',
            'images/joe-dimaggio.jpg',
            'images/edgar-allan-poe.jpg',
            'images/arthur-conan-doyle.jpg',
            'images/william-henry-harrison.jpg',
            'images/john-tyler.jpg',
            'images/james-k-polk.jpg',
            'images/zachary-taylor.jpg',
            'images/andrew-johnson.jpg',
            'images/grover-cleveland.jpg',
            'images/rutherford-b-hayes.jpg',
            'images/moses-harry-horowitz.jpg',
            'images/rod-serling.jpg',
            'images/bessie-smith.jpg',
            'images/jean-phillipe-rameau.jpg',
            'images/vladimir-nabakov.jpg',
            'images/michael-landon.jpg'
        ];

        let butt = document.querySelector("button");
        let randy = 0;
        let max = phrases.length;
        function generatePhrase(phraseArray, imageArray) {
            randy = Math.floor(Math.random() * Math.floor(max));
            document.getElementById("pic").src = imageArray[randy];
            document.getElementById("pic").style.width = "400px";
            document.getElementById("quote").innerHTML = phraseArray[randy];
        }